version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: install required dependencies
          command: |
            sudo apt-get update
            sudo apt install libxml2-utils
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: |
            export TAG="$(echo "cat //*[local-name()='project']/*[local-name()='version']" | xmllint --shell pom.xml | sed '/^\/ >/d' | sed 's/<[^>]*.//g')"
            export IMAGE_NAME="$(echo "cat //*[local-name()='project']/*[local-name()='name']" | xmllint --shell pom.xml | sed '/^\/ >/d' | sed 's/<[^>]*.//g')"
            echo "Application version : $TAG"
            echo "Application name : $IMAGE_NAME"
            sudo docker image build --tag $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            sudo docker login -u $DOCKER_LOGIN -p $DOCKERHUB_TOKEN
            sudo docker push --tag $DOCKER_LOGIN/$IMAGE_NAME:$TAG
workflows:
  build-test-publish-to-dockerhub:
    jobs:
      - build-and-test