version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
        auth:
            username: $DOCKER_LOGIN
            password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: install required dependencies
          command: |
            sudo apt-get update
            sudo apt install libxml2-utils
      - run:
          name: Build Docker image
          command: |
            export TAG="$(echo "cat //*[local-name()='project']/*[local-name()='version']" | xmllint --shell pom.xml | sed '/^\/ >/d' | sed 's/<[^>]*.//g')"
            export IMAGE_NAME="$(echo "cat //*[local-name()='project']/*[local-name()='name']" | xmllint --shell pom.xml | sed '/^\/ >/d' | sed 's/<[^>]*.//g')"
            echo "Application version : $TAG"
            echo "Application name : $IMAGE_NAME"
            docker image build --tag $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            echo $DOCKERHUB_TOKEN|docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME:$TAG
workflows:
  build-test-publish-to-dockerhub:
    jobs:
      - build-and-test