version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  build-docker-image:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: install required dependencies
          command: |
            sudo apt-get update
            sudo apt install libxml2-utils
            sudo apt install docker
      - run: 
          name: Get Application version from pom.xml
          command: |
            export TAG="$(echo "cat //*[local-name()='project']/*[local-name()='version']" | xmllint --shell pom.xml | sed '/^\/ >/d' | sed 's/<[^>]*.//g')"
            export MAGE_NAME="$(echo "cat //*[local-name()='project']/*[local-name()='name']" | xmllint --shell pom.xml | sed '/^\/ >/d' | sed 's/<[^>]*.//g')"
            echo "Application version : $TAG"
      - run:
          name: Build Docker image
          command: |
            docker image build -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            echo $DOCKERHUB_TOKEN | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/$IMAGE_NAME:$TAG
workflows:
  build-test-publish-to-dockerhub:
    jobs:
      - build-and-test
      - build-docker-image
        requires:
          - build-and-test